### ISSUE TITLE
OSError: Initializing from file failed.

### ISSUE THREAD

**Issue by IronLavender** [idiap/semiblindpsfdeconv#1]
Thanks for your sharing! But in data_utils.py, 
```
def load_crops(batch_size, listname_train = "./filelistpsf_train_regression_gaussian", listname_test="./filelistpsf_test_regression_gaussian",
               foldername_train = "./psf_train_regression_gaussian", foldername_test = "./psf_test_regression_gaussian")
```
These 4 files were not found. So the codes report an error, OSError: Initializing from file failed.
Could you please upload them?

**Comment by ashajkofci** [comment]
Hello ! These are just the name of training files and the name of the training data folders. You can adapt the arguments as you see fit.
